spring:
  profiles:
    active: test

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,loggers
# management.endpoint.<function>.enabled=true
# management.endpoint.<function>.show-details=always
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
    loggers:
      enabled: true
